name: Run Tests

on:
  workflow_dispatch:  # Listens for repository_dispatch event from the dev repo

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Run Tests
      run: |
        # Add your test commands here
        yarn install
        yarn run
