name: Run Tests

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually or via API
  push:               # Optional: can also run on pushes
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        yarn install
        yarn playwright install chromium

    - name: Run Tests
      run: yarn run test

    - name: Generate Allure Report
      run: |
        allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
    
    - name: Trigger Repository B Workflow
      run: |
        curl -X POST \
        -H "Authorization: token ${{ secrets.PAT }}" \
        -H "Accept: application/vnd.github.everest-preview+json" \
        https://api.github.com/repos/shivankartft/react-redux-realworld-example-app/actions/workflows/run-report.yml/dispatches \
        -d '{"ref":"main"}'

