name: Run Tests

on:
  repository_dispatch:  # Listens for a dispatch event from the dev repo

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        yarn install
        yarn playwright install

    - name: Run Tests
      run: yarn run test
