name: Run Tests

on:
  workflow_dispatch:  # This allows the workflow to be triggered manually or via API
  push:               # Optional: can also run on pushes
    branches:
      - master

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: |
        yarn install
        yarn playwright install chromium
    
    - name: Install Java
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre

    - name: Install Allure Command-Line Tool
      run: |
        # Install Java if it's not already installed
        sudo apt-get update
        sudo apt-get install -y openjdk-11-jre
        # Download and set up Allure
        wget -q https://github.com/allure-framework/allure2/releases/download/2.17.3/allure-2.17.3.tgz
        tar -xzf allure-2.17.3.tgz
        sudo mv allure-2.17.3 /opt/allure
        echo 'export PATH=$PATH:/opt/allure/bin' >> $GITHUB_ENV
        echo "/opt/allure/bin" >> $GITHUB_PATH

    - name: Run Tests
      run: yarn run test
      continue-on-error: true

    - name: Generate Allure Report
      run: allure generate allure-results --clean -o allure-report

    - name: Upload Allure Report
      uses: actions/upload-artifact@v3
      with:
        name: allure-report
        path: allure-report
    
    # - name: Trigger Repository B Workflow
    #   run: |
    #     curl -X POST \
    #     -H "Authorization: token ${{ secrets.PAT }}" \
    #     -H "Accept: application/vnd.github.everest-preview+json" \
    #     https://api.github.com/repos/shivankartft/react-redux-realworld-example-app/actions/workflows/run-report.yml/dispatches \
    #     -d '{"ref":"master"}'

    - name: Upload Allure Report to GitHub Pages
      run: |
        mkdir -p gh-pages
        cp -r allure-report gh-pages/
        cd gh-pages
        git init
        git config user.name "${{github.actor}}"
        git config user.email "${{github.actor}}@tftus.com"
        git add .
        git commit -m "Update Allure Report"
        git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages:gh-pages